# Generated by Django 5.2.9 on 2025-12-24 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_ack_date_invoice_ack_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
